# Generated by Django 4.2.9 on 2024-02-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_userdriver_groups_and_more"),
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("quantity", models.IntegerField()),
                ("phone", models.CharField(default="", max_length=15)),
                ("details", models.TextField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userfarmer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
    ]
