# Generated by Django 4.2.9 on 2024-02-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_alter_vehicle_driver"),
        ("farmer", "0002_booking_delete_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicle",
            ),
        ),
    ]
