# Generated by Django 4.2.9 on 2024-02-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmer", "0004_booking_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("รออนุมัติ", "รออนุมัติ"),
                    ("อนุมัติแล้ว", "อนุมัติแล้ว"),
                    ("ไม่อนุมัติ", "ไม่อนุมัติ"),
                    ("กำลังดำเนินการ", "กำลังดำเนินการ"),
                    ("เสร็จสิ้น", "เสร็จสิ้น"),
                    ("ยกเลิก", "ยกเลิก"),
                ],
                default="รออนุมัติ",
                max_length=100,
            ),
        ),
    ]
