# Generated by Django 4.2.9 on 2024-02-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0023_alter_userdriver_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
    ]
