# Generated by Django 4.2.9 on 2024-02-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[("Sack", "แบบรองกระสอบ"), ("Bucket", "แบบถังอุ้ม")],
                max_length=10,
            ),
        ),
    ]
