# Generated by Django 5.0 on 2023-12-20 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmer",
            old_name="name_surname",
            new_name="fullname",
        ),
    ]
