# Generated by Django 5.0 on 2023-12-21 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
