# Generated by Django 5.0 on 2023-12-21 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_delete_customuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="Farmer",
        ),
    ]
