# Generated by Django 5.0 on 2023-12-21 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_farmer_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Farmer",
        ),
    ]
