# Generated by Django 5.0 on 2023-12-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0015_delete_farmer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modeltest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="media")),
            ],
        ),
    ]
