# Generated by Django 5.0 on 2023-12-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_userdriver_userfarmer_delete_modeltest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdriver",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userfarmer",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
