# Generated by Django 5.0 on 2023-12-21 10:40

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_userdriver_address_userfarmer_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdriver",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userdriver",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userfarmer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userfarmer",
            name="name",
        ),
        migrations.AlterField(
            model_name="userdriver",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="userfarmer",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
