# Generated by Django 5.0 on 2023-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_remove_userdriver_address_remove_userdriver_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdriver",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userdriver",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userfarmer",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userfarmer",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdriver",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="userfarmer",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
