# Generated by Django 4.2.9 on 2024-02-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0022_userdriver_phone_userfarmer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdriver",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="accounts_driver_groups",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
        migrations.AlterField(
            model_name="userdriver",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="accounts_driver_user_permissions",
                to="auth.permission",
                verbose_name="User Permissions",
            ),
        ),
        migrations.AlterField(
            model_name="userfarmer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="accounts_farmer_groups",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
        migrations.AlterField(
            model_name="userfarmer",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="farmer_users_permissions",
                to="auth.permission",
                verbose_name="User Permissions",
            ),
        ),
    ]
