# Generated by Django 5.0 on 2023-12-22 01:58

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=driver.models.vehicle_image_path
            ),
        ),
    ]
