# Generated by Django 5.0 on 2023-12-22 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0002_alter_vehicle_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="make",
            new_name="name",
        ),
    ]
