# Generated by Django 4.2.9 on 2024-02-13 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0002_jobschedule_booking"),
    ]

    operations = []
