# Generated by Django 4.2.9 on 2024-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0006_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="user",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
    ]
