# Generated by Django 4.2.9 on 2024-02-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0023_alter_userdriver_groups_and_more"),
        ("driver", "0007_remove_driver_user_delete_vehicle_delete_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="accounts.userdriver",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("work_experience", models.CharField(max_length=255)),
            ],
        ),
    ]
