# Generated by Django 4.2.9 on 2024-02-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_userdriver_groups_and_more"),
        ("driver", "0009_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_images/")),
                ("model", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("province", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userdriver",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="user",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
