# Generated by Django 4.2.9 on 2024-02-14 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_userdriver_groups_and_more"),
        ("driver", "0010_drivercar_remove_vehicle_user_delete_driver_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DriverCar",
            new_name="Car",
        ),
    ]
